[build]
  publish = "."
  command = "echo 'Building Static Site'"

[[redirects]]
  from = "/vendas"
  to = "/vendas.html"
  status = 200

[[redirects]]
  from = "/sobre"
  to = "/sobre.html"
  status = 200

[[redirects]]
  from = "/aprovacao/:token"
  to = "/aprovacao.html?id=:token"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"
